const LOCAL_STORAGE_CHATS_KEY = "chats";
const LOCAL_STORAGE_CREDENTIALS_KEY = "credentials";
const LOCAL_STORAGE_USER_PHOTO = "userPhoto";
const INTELLIGENCE_DEFAULT = "Привет! Я использую WhatsApp.";
const LOCAL_STORAGE_USER_NAME = "userName";
const LOCAL_STORAGE_INTELLIGENCE = "intelligence";

export {
  LOCAL_STORAGE_USER_PHOTO,
  LOCAL_STORAGE_CREDENTIALS_KEY,
  LOCAL_STORAGE_CHATS_KEY,
  INTELLIGENCE_DEFAULT,
  LOCAL_STORAGE_USER_NAME,
  LOCAL_STORAGE_INTELLIGENCE,
};
